const productos = [
    {
        nombre: "Small Gratitude Everyday",
        precio: 800,
        imagen: "../images/product1.jpg",
        id: 1,
        descripcion: "Una vida feliz siendo agradecido",
        product: "product-1"
    },
    {
        nombre: "The Modern Kitchen",
        precio: 950,
        imagen: "../images/product2.jpg",
        id: 2,
        descripcion: "Recetas para inspirar al chef  interior",
        product: "product-2",
    },
    {
        nombre: "Guide to Fitness for Woman",
        precio: 899,
        imagen: "../images/product3.jpg",
        id: 3,
        descripcion: "Guía fitness para principiantes",
        product: "product-3",
    },
    {
        nombre: "How to Manage Your Energy",
        precio: 650,
        imagen: "../images/product4.jpg",
        id: 4,
        descripcion: "Hacé que tu cuerpo trabaje para ti",
        product: "product-4",
    },
    {
        nombre: "Benefits of Meditation",
        precio: 1350,
        imagen: "../images/product5.jpg",
        id: 5,
        descripcion: "Cómo entrenar tu mente",
        product: "product-5",
    },
    {
        nombre: "Daily Food Journal",
        precio: 1290,
        imagen: "../images/product6.jpg",
        id: 6,
        descripcion: "Registra tus comidas y vive mejor",
        product: "product-6",
    },
    ];  